table Stores
	lineageTag: af32a1d5-99e3-4b32-aa67-26fec54c29fc
	ordinal: 3

	partition Stores-9adb2fe5-82cc-4247-9cbf-199daa1f6820 = M
		mode: Import
		expression:=
			let
			    Source = Access.Database(File.Contents("C:\Users\owend\Documents\ContosoSalesV31_64bit.accdb")),
			    _DimStores = Source{[Schema="",Item="DimStores"]}[Data],
			    #"Removed Columns" = Table.RemoveColumns(_DimStores,{"StoreManager", "CloseDate", "OpenDate", "ZipCode", "ZipCodeExtension", "StorePhone", "StoreFax", "AddressLine1", "AddressLine2", "LastRemodelDate", "GeoLocation", "Geometry", "ETLLoadID", "LoadDate", "UpdateDate", "EntityKey", "StoreDescription"})
			in
			    #"Removed Columns"

	column StoreKey
		dataType: Double
		isDataTypeInferred: false
		isHidden
		lineageTag: a1c636ef-ca76-4181-ba5a-a8aef0202724
		sourceColumn: StoreKey
		summarizeBy: None

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column GeographyKey
		dataType: Double
		isDataTypeInferred: false
		isHidden
		lineageTag: 103e05db-8d94-4f32-92a9-b0b3f6b79440
		sourceColumn: GeographyKey
		summarizeBy: None

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column StoreType
		dataType: String
		isDataTypeInferred: false
		lineageTag: 5f5a23de-61e3-4b90-b2a8-e3f481ae7743
		sourceColumn: StoreType
		summarizeBy: None

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column StoreName
		dataType: String
		isDataTypeInferred: false
		lineageTag: 880bac7d-2cb1-4c3a-a44d-e2c9a791479c
		sourceColumn: StoreName
		summarizeBy: None

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column Status
		dataType: String
		isDataTypeInferred: false
		lineageTag: 5e8012ff-f745-43c4-aef1-d606643fffb7
		sourceColumn: Status
		summarizeBy: None

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column CloseReason
		dataType: String
		isDataTypeInferred: false
		lineageTag: 853d2d36-f0a8-4eda-ad44-e261cabecfe8
		sourceColumn: CloseReason
		summarizeBy: None

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column EmployeeCount
		dataType: Double
		isDataTypeInferred: false
		lineageTag: 7e848515-412f-41c6-a527-cae050c18944
		sourceColumn: EmployeeCount
		summarizeBy: Sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column SellingAreaSize
		dataType: Double
		isDataTypeInferred: false
		lineageTag: c19be1aa-2111-4e18-8b79-bcb402be2378
		sourceColumn: SellingAreaSize
		summarizeBy: Sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	annotation ColumnsMetadata = {"Columns":[{"Name":"StoreKey","Id":"Server.Database\\/1/File/c:\\\\users\\\\owend\\\\documents\\\\contososalesv31_64bit.accdb//DimStores.{StoreKey,0}"},{"Name":"GeographyKey","Id":"Server.Database\\/1/File/c:\\\\users\\\\owend\\\\documents\\\\contososalesv31_64bit.accdb//DimStores.{GeographyKey,1}"},{"Name":"StoreType","Id":"Server.Database\\/1/File/c:\\\\users\\\\owend\\\\documents\\\\contososalesv31_64bit.accdb//DimStores.{StoreType,3}"},{"Name":"StoreName","Id":"Server.Database\\/1/File/c:\\\\users\\\\owend\\\\documents\\\\contososalesv31_64bit.accdb//DimStores.{StoreName,4}"},{"Name":"Status","Id":"Server.Database\\/1/File/c:\\\\users\\\\owend\\\\documents\\\\contososalesv31_64bit.accdb//DimStores.{Status,6}"},{"Name":"CloseReason","Id":"Server.Database\\/1/File/c:\\\\users\\\\owend\\\\documents\\\\contososalesv31_64bit.accdb//DimStores.{CloseReason,16}"},{"Name":"EmployeeCount","Id":"Server.Database\\/1/File/c:\\\\users\\\\owend\\\\documents\\\\contososalesv31_64bit.accdb//DimStores.{EmployeeCount,17}"},{"Name":"SellingAreaSize","Id":"Server.Database\\/1/File/c:\\\\users\\\\owend\\\\documents\\\\contososalesv31_64bit.accdb//DimStores.{SellingAreaSize,18}"}]}

	annotation PBI_ResultType = Table

