table Product
	lineageTag: e3345f41-5862-4a86-a028-621c14128769

	column ProductName
		dataType: string
		lineageTag: 4fd87a6f-7af2-45cd-be1c-a69efa26e931
		summarizeBy: none
		sourceColumn: ProductName

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column ProductDescription
		dataType: string
		lineageTag: f7072a91-cfd4-4d0e-aa34-60e8819f827f
		summarizeBy: none
		sourceColumn: ProductDescription

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column Manufacturer
		dataType: string
		lineageTag: f07278cd-f13a-4417-8f13-813bbec68aaf
		summarizeBy: none
		sourceColumn: Manufacturer

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column BrandName
		dataType: string
		lineageTag: e3e0a873-f50e-49b0-93ec-fd0a1b755f4d
		summarizeBy: none
		sourceColumn: BrandName

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column ClassName
		dataType: string
		lineageTag: 669bd24e-9941-430b-8df1-fb2702d974b0
		summarizeBy: none
		sourceColumn: ClassName

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column UnitCost
		dataType: decimal
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: b9c49037-0a70-4444-bc76-961f5ba411ea
		summarizeBy: sum
		sourceColumn: UnitCost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column UnitPrice
		dataType: decimal
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 3b98125a-d8f9-4328-b47a-f70e7a50ce83
		summarizeBy: sum
		sourceColumn: UnitPrice

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column ProductKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: b669f48f-cbf4-47ac-9056-9ff50f9ef906
		summarizeBy: none
		sourceColumn: ProductKey

		annotation SummarizationSetBy = Automatic

	column ProductSubcategoryKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: fa463c13-b92b-4836-8b32-05aa386c3f8e
		summarizeBy: none
		sourceColumn: ProductSubcategoryKey

		annotation SummarizationSetBy = Automatic

	partition Product-72fec1c0-1b5e-42ad-8638-c5ae2a2df004 = m
		mode: import
		source =
				let
				    Source = Access.Database(File.Contents("C:\Users\owend\Documents\ContosoSalesV31_64bit.accdb")),
				    _DimProduct = Source{[Schema="",Item="DimProduct"]}[Data],
				    #"Reordered Columns" = Table.ReorderColumns(_DimProduct,{"ProductKey", "ProductName", "ProductSubcategoryKey", "Manufacturer", "BrandName", "ClassName", "ProductLabel", "ProductDescription", "ClassID", "StyleID", "StyleName", "ColorID", "ColorName", "Size", "SizeRange", "SizeUnitMeasureID", "Weight", "WeightUnitMeasureID", "UnitOfMeasureID", "UnitOfMeasureName", "StockTypeID", "StockTypeName", "UnitCost", "UnitPrice", "AvailableForSaleDate", "StopSaleDate", "Status", "ImageURL", "ProductURL", "ETLLoadID", "LoadDate", "UpdateDate"}),
				    #"Removed Other Columns" = Table.SelectColumns(#"Reordered Columns",{"ProductKey", "ProductName", "ProductSubcategoryKey", "Manufacturer", "BrandName", "ClassName", "ProductDescription", "UnitCost", "UnitPrice"})
				in
				    #"Removed Other Columns"

	annotation ColumnsMetadata = {"Columns":[{"Name":"ProductKey","Id":"Server.Database\\/1/File/c:\\\\users\\\\owend\\\\documents\\\\contososalesv31_64bit.accdb//DimProduct.{ProductKey,0}"},{"Name":"ProductName","Id":"Server.Database\\/1/File/c:\\\\users\\\\owend\\\\documents\\\\contososalesv31_64bit.accdb//DimProduct.{ProductName,2}"},{"Name":"ProductSubcategoryKey","Id":"Server.Database\\/1/File/c:\\\\users\\\\owend\\\\documents\\\\contososalesv31_64bit.accdb//DimProduct.{ProductSubcategoryKey,4}"},{"Name":"Manufacturer","Id":"Server.Database\\/1/File/c:\\\\users\\\\owend\\\\documents\\\\contososalesv31_64bit.accdb//DimProduct.{Manufacturer,5}"},{"Name":"BrandName","Id":"Server.Database\\/1/File/c:\\\\users\\\\owend\\\\documents\\\\contososalesv31_64bit.accdb//DimProduct.{BrandName,6}"},{"Name":"ClassName","Id":"Server.Database\\/1/File/c:\\\\users\\\\owend\\\\documents\\\\contososalesv31_64bit.accdb//DimProduct.{ClassName,8}"},{"Name":"ProductDescription","Id":"Server.Database\\/1/File/c:\\\\users\\\\owend\\\\documents\\\\contososalesv31_64bit.accdb//DimProduct.{ProductDescription,3}"},{"Name":"UnitCost","Id":"Server.Database\\/1/File/c:\\\\users\\\\owend\\\\documents\\\\contososalesv31_64bit.accdb//DimProduct.{UnitCost,22}"},{"Name":"UnitPrice","Id":"Server.Database\\/1/File/c:\\\\users\\\\owend\\\\documents\\\\contososalesv31_64bit.accdb//DimProduct.{UnitPrice,23}"}]}

	annotation PBI_ResultType = Table

