table Channel
	lineageTag: 567a34b1-5e88-48bf-8147-e67409800671

	column Channel
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 1dd83ccc-1036-4cef-8aac-aecd8de8abbd
		summarizeBy: none
		sourceColumn: Channel

		annotation SummarizationSetBy = Automatic

	column ChannelName
		dataType: string
		lineageTag: fbd376a2-9d82-46b6-abe0-4c0bf9e5afce
		summarizeBy: none
		sourceColumn: ChannelName

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	partition Channel-3836f8fd-e2fe-46b4-9aa4-9956499fe1dc = m
		mode: import
		source =
				let
				    Source = Access.Database(File.Contents("C:\Users\owend\Documents\ContosoSalesV31_64bit.accdb")),
				    _DimChannel = Source{[Schema="",Item="DimChannel"]}[Data],
				    #"Removed Columns" = Table.RemoveColumns(_DimChannel,{"ETLLoadID", "LoadDate"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Removed Columns",{{"ChannelKey", "Channel"}}),
				    #"Removed Columns1" = Table.RemoveColumns(#"Renamed Columns",{"ChannelLabel", "ChannelDescription", "UpdateDate"})
				in
				    #"Removed Columns1"

	annotation ColumnsMetadata = {"Columns":[{"Name":"Channel","Id":"Server.Database\\/1/File/c:\\\\users\\\\owend\\\\documents\\\\contososalesv31_64bit.accdb//DimChannel.{ChannelKey,0}"},{"Name":"ChannelName","Id":"Server.Database\\/1/File/c:\\\\users\\\\owend\\\\documents\\\\contososalesv31_64bit.accdb//DimChannel.{ChannelName,2}"}]}

	annotation PBI_ResultType = Table

